openapi: 3.0.3

info:
  title: Payment Notice Microservice
  version: 10.0.0
  description: Payment Notice Microservice for Multi-channel Integration Layer of SW Client Project
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it

servers:
  - description: DEV
    url: https://mil-d-apim.azure-api.net/mil-payment-notice

paths:
  /paymentNotices/{qrCode}:
    parameters:
      - $ref: 'common.yaml#/components/parameters/RequestId'
      - $ref: 'common.yaml#/components/parameters/Version'
      - $ref: 'common.yaml#/components/parameters/AcquirerId'
      - $ref: 'common.yaml#/components/parameters/Channel'
      - $ref: 'common.yaml#/components/parameters/MerchantId'
      - $ref: 'common.yaml#/components/parameters/TerminalId'
      - name: qrCode
        description: Base64Url of the string encoded by the QR-code. This is due to a bug of Azure routing system which decodes %2F before routing the request.
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/QrCodeBase64UrlEnc'

    # ------------------------------------------------------
    # Verify a payment notice by QR-code
    # ------------------------------------------------------
    get:
      operationId: verifyByQrCode
      summary: Verify a payment notice by QR-code
      security: 
        - oAuth2: [ verifyByQrCode ]
      responses:
        "200":
          $ref: '#/components/responses/VerifyProcessed'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Activate the payment of a notice by QR-code
    # ------------------------------------------------------
    patch:
      operationId: activateByQrCode
      summary: Activate the payment of a notice by QR-code
      security: 
        - oAuth2: [ activateByQrCode ]
      requestBody:
        $ref: '#/components/requestBodies/Activate'
      responses:
        "200":
          $ref: '#/components/responses/ActivateProcessed'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

  /paymentNotices/{paTaxCode}/{noticeNumber}:
    parameters:
      - $ref: 'common.yaml#/components/parameters/RequestId'
      - $ref: 'common.yaml#/components/parameters/Version'
      - $ref: 'common.yaml#/components/parameters/AcquirerId'
      - $ref: 'common.yaml#/components/parameters/Channel'
      - $ref: 'common.yaml#/components/parameters/MerchantId'
      - $ref: 'common.yaml#/components/parameters/TerminalId'
      - name: paTaxCode
        description: Tax code of the creditor company
        in: path
        required: true
        schema:
          $ref: 'common-payment-notice.yaml#/components/schemas/PaTaxCode'
      - name: noticeNumber
        description: Notice number
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/NoticeNumber'

    # ------------------------------------------------------
    # Verify a payment notice by PA tax code and notice
    # number
    # ------------------------------------------------------
    get:
      operationId: verifyByTaxCodeAndNoticeNumber
      summary: Verify a payment notice by PA tax code and notice number
      security: 
        - oAuth2: [ verifyByTaxCodeAndNoticeNumber ]
      responses:
        "200":
          $ref: '#/components/responses/VerifyProcessed'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Activate the payment of a notice by PA tax code and
    # notice number
    # ------------------------------------------------------
    patch:
      operationId: activateByTaxCodeAndNoticeNumber
      summary: Activate the payment of a notice by PA tax code and notice number
      security: 
        - oAuth2: [ activateByTaxCodeAndNoticeNumber ]
      requestBody:
        $ref: '#/components/requestBodies/Activate'
      responses:
        "200":
          $ref: '#/components/responses/ActivateProcessed'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment notice not found
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

  /payments:
    # ------------------------------------------------------
    # Close the payment of a set of notices
    # ------------------------------------------------------
    post:
      operationId: close
      summary: Close the payment of a set of notices
      security: 
        - oAuth2: [ close ]
      parameters:
        - $ref: 'common.yaml#/components/parameters/RequestId'
        - $ref: 'common.yaml#/components/parameters/Version'
        - $ref: 'common.yaml#/components/parameters/AcquirerId'
        - $ref: 'common.yaml#/components/parameters/Channel'
        - $ref: 'common.yaml#/components/parameters/MerchantId'
        - $ref: 'common.yaml#/components/parameters/TerminalId'
      requestBody:
        $ref: '#/components/requestBodies/Close'
      responses:
        "200":
          $ref: '#/components/responses/OkCloseProcessed'
        "202":
          description: This response is returned for KO close only
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

  /payments/{transactionId}:
    parameters:
      - name: transactionId
        description: Transaction ID
        in: path
        required: true
        schema:
          $ref: 'common-payment-notice.yaml#/components/schemas/TransactionId'

    # ------------------------------------------------------
    # Retrieve the status of the payment of a set of payment
    # notices
    # ------------------------------------------------------
    get:
      operationId: getPaymentStatus
      summary: Retrieve the status of the payment of a set of payment notices
      security: 
        - oAuth2: [ getPaymentStatus ]
      parameters:
        - $ref: 'common.yaml#/components/parameters/RequestId'
        - $ref: 'common.yaml#/components/parameters/Version'
        - $ref: 'common.yaml#/components/parameters/AcquirerId'
        - $ref: 'common.yaml#/components/parameters/Channel'
        - $ref: 'common.yaml#/components/parameters/MerchantId'
        - $ref: 'common.yaml#/components/parameters/TerminalId'
      responses:
        "200":
          $ref: '#/components/responses/PaymentStatus'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Payment status not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

    # ------------------------------------------------------
    # Receive from the Nodo the result of the payment of a
    # set of payment notices
    # ------------------------------------------------------
    post:
      operationId: receivePaymentStatus
      tags: [ internal ]
      summary: Receive from the Nodo the result of the payment of a set of payment notices. This API is invoked by the Nodo for sendPaymentResult.
      security:
        - ApiKeyAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/PaymentStatusByNodo'
      responses:
        "200":
          $ref: '#/components/responses/PaymentStatusReceived'
        "400":
          $ref: 'common.yaml#/components/responses/Error'
        "401":
          description: API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          $ref: '#/components/responses/TransactionNotFound'
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          $ref: 'common.yaml#/components/responses/Error'
        default:
          description: Unexpected error

components:
  # ========================================================
  # Schemas
  # ========================================================
  schemas:
    # ------------------------------------------------------
    # Basic types
    # ------------------------------------------------------
    AllOrNothingOutcome:
      description: Dual values (OK or KO) outcome
      type: string
      enum:
        - OK
        - KO
      example: "OK"
    
    Company:
      description: Name of the creditor company
      type: string
      pattern: "^[ -~]{1,140}$"
      example: "ASL Roma"

    CreditorReferenceId:
      description: ID for the creditor company
      type: string
      pattern: "^[ -~]{1,35}$"
      example: "4839d50603fssfW5X"

    Debtor:
      description: Debtor unstructured data
      type: string
      pattern: "^[ -~]{0,1024}$"
      example: "Mario Rossi"

    Description:
      description: Payment notice description
      type: string
      pattern: "^[ -~]{1,140}$"
      example: "Health ticket for chest x-ray"

    DueDate:
      description: Expiration date of the payment notice
      type: string
      format: date
      maxLength: 10
      example: "2022-11-30"

    IdempotencyKey:
      description: Idempotency key for activate request
      type: string
      pattern: "^[0-9]{11}_[a-zA-Z0-9]{10}$"
      example: "47583764545_Ahf479elk0"

    Note:
      description: Payment notice note
      type: string
      pattern: "^[ -~]{1,210}$"
      example: "This is a payment notice"

    NoticeNumber:
      description: Notice number
      type: string
      pattern: "^[0-9]{18}$"
      example: "485564829563528563"

    Office:
      description: Name of the creditor company office
      type: string
      pattern: "^[ -~]{1,140}$"
      example: "Ufficio di Roma"

    OkOutcome:
      description: Constant value (OK) outcome
      enum:
        - OK
      type: string
      example: "OK"

    KoOutcome:
      description: Outcome returned to verify and activate operations when something went wrong
      type: string
      enum:
        - NOTICE_GLITCH               # Spiacenti, c'è un problema tecnico con questo avviso.
        - WRONG_NOTICE_DATA           # Spiacenti, i dati dell’avviso non sono corretti.
        - CREDITOR_PROBLEMS           # Spiacenti, l’Ente Creditore sta avendo problemi nella risposta.
        - PAYMENT_ALREADY_IN_PROGRESS # Il pagamento è già in corso, riprova fra qualche minuto.
        - EXPIRED_NOTICE              # Spiacenti, l’avviso è scaduto e non è più possibile pagarlo.
        - REVOKED_NOTICE              # Spiacenti, l’Ente Creditore ha revocato questo avviso.
        - NOTICE_ALREADY_PAID         # Questo avviso è stato già pagato!
        - UNKNOWN_NOTICE              # Avviso sconosciuto.
        - UNEXPECTED_ERROR            # Spiacenti, si è verificato un errore imprevisto.
      example: "NOTICE_GLITCH"

    PaymentToken:
      description: ID of the payment activation
      type: string
      pattern: "^[ -~]{1,35}$"
      example: "648fhg36s95jfg7DS"

    QrCode:
      description: String encoded by the QR-code
      type: string
      pattern: "^[ -~]{6}\\|[ -~]{3}\\|[0-9]{18}\\|[0-9]{11}\\|[0-9]{2,11}$"
      example: "PAGOPA|002|000000000000000000|00000000000|9999"

    QrCodeBase64UrlEnc:
      description: Base64Url of the string encoded by the QR-code. This is due to a bug of Azure routing system which decodes %2F before routing the request.
      type: string
      pattern: "^[a-zA-Z0-9_-]{32,128}$"
      example: "UEFHT1BBfDAwMnwwMDAwMDAwMDAwMDAwMDAwMDB8MDAwMDAwMDAwMDB8OTk5OQ"

    # ------------------------------------------------------
    # Common complex types
    # ------------------------------------------------------
    PaymentStatus:
      description: Payment status communicated by the Nodo
      type: object
      additionalProperties: false
      properties:
        outcome:
          $ref: '#/components/schemas/AllOrNothingOutcome'
        paymentDate:
          description: Notification timestamp
          type: string
          format: date-time
          maxLength: 19
        payments:
          description: Details of payment notices
          type: array
          maxItems: 5
          items:
            $ref: '#/components/schemas/PaymentDetails'
      required:
        - outcome
        - paymentDate
        - payments
      example:
        outcome: "OK"
        paymentDate: "2022-11-12T08:53:55"
        payments:
          - paymentToken: "648fhg36s95jfg7DS"
            description: "Health ticket for chest x-ray"
            creditorReferenceId: "4839d50603fssfW5X"
            paTaxCode: "15376371009"
            company: "ASL Roma"
            office: "Ufficio di Roma"
            debtor: "Mario Rossi"

    PaymentStatusByNodo:
      description: Payment status communicated by the Nodo
      type: object
      additionalProperties: false
      properties:
        outcome:
          $ref: '#/components/schemas/AllOrNothingOutcome'
        paymentDate:
          description: Notification timestamp
          type: string
          format: date-time
          maxLength: 19
        payments:
          description: Details of payment notices
          type: array
          maxItems: 5
          items:
            $ref: '#/components/schemas/PaymentDetailsByNodo'
      required:
        - outcome
        - paymentDate
        - payments
      example:
        outcome: "OK"
        paymentDate: "2022-11-12T08:53:55"
        payments:
          - paymentToken: "648fhg36s95jfg7DS"
            description: "Health ticket for chest x-ray"
            creditorReferenceId: "4839d50603fssfW5X"
            fiscalCode: "15376371009"
            company: "ASL Roma"
            office: "Ufficio di Roma"
            debtor: "Mario Rossi"
            
    PaymentDetails:
      description: Details of a payment notice
      type: object
      additionalProperties: false
      properties:
        paymentToken:
          $ref: '#/components/schemas/PaymentToken'
        description:
          $ref: '#/components/schemas/Description'
        creditorReferenceId:
          $ref: '#/components/schemas/CreditorReferenceId'
        paTaxCode:
          $ref: 'common-payment-notice.yaml#/components/schemas/PaTaxCode'
        company:
          $ref: '#/components/schemas/Company'
        office:
          $ref: '#/components/schemas/Office'
        debtor:
          $ref: '#/components/schemas/Debtor'
      example:
        paymentToken: "648fhg36s95jfg7DS"
        description: "Health ticket for chest x-ray"
        creditorReferenceId: "4839d50603fssfW5X"
        paTaxCode: "15376371009"
        company: "ASL Roma"
        office: "Ufficio di Roma"
        debtor: "Mario Rossi"
    
    PaymentDetailsByNodo:
      description: Details of a payment notice communicated by the Nodo
      type: object
      additionalProperties: false
      properties:
        paymentToken:
          $ref: '#/components/schemas/PaymentToken'
        description:
          $ref: '#/components/schemas/Description'
        creditorReferenceId:
          $ref: '#/components/schemas/CreditorReferenceId'
        fiscalCode:
          $ref: 'common-payment-notice.yaml#/components/schemas/PaTaxCode'
        company:
          $ref: '#/components/schemas/Company'
        office:
          $ref: '#/components/schemas/Office'
        debtor:
          $ref: '#/components/schemas/Debtor'
      example:
        paymentToken: "648fhg36s95jfg7DS"
        description: "Health ticket for chest x-ray"
        creditorReferenceId: "4839d50603fssfW5X"
        fiscalCode: "15376371009"
        company: "ASL Roma"
        office: "Ufficio di Roma"
        debtor: "Mario Rossi"
        
    TrxNotFoundOutcome:
      description: Constant value (PAYMENT_NOT_FOUND) outcome
      type: string
      enum:
        - PAYMENT_NOT_FOUND
      example: "PAYMENT_NOT_FOUND"
    
    VerifyOrActivateKo:
      description: Response to verify or activate payment notice when something went wrong
      type: object
      properties:
        outcome:
          $ref: '#/components/schemas/KoOutcome'
      required:
        - outcome
      example:
        outcome: "NOTICE_GLITCH"

    # ------------------------------------------------------
    # Complex types for verifyByQrCode and
    # verifyByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    VerifyOk:
      description: Response to verify payment notice when all went ok
      type: object
      properties:
        outcome:
          $ref: '#/components/schemas/OkOutcome'
        amount:
          $ref: 'common-payment-notice.yaml#/components/schemas/EuroCents'
        dueDate:
          $ref: '#/components/schemas/DueDate'
        note:
          $ref: '#/components/schemas/Note'
        description:
          $ref: '#/components/schemas/Description'
        company:
          $ref: '#/components/schemas/Company'
        office:
          $ref: '#/components/schemas/Office'
        paTaxCode:
          $ref: 'common-payment-notice.yaml#/components/schemas/PaTaxCode'
        noticeNumber:
          $ref: '#/components/schemas/NoticeNumber'
      required:
        - outcome
        - amount
        - paTaxCode
        - noticeNumber
      example:
        outcome: "OK"
        amount: 12345
        paTaxCode: "15376371009"
        noticeNumber: "485564829563528563"

    # ------------------------------------------------------
    # Complex types for activateByQrCode and
    # activateByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    ActivateOk:
      description: Response to activate payment notice when all went ok
      type: object
      properties:
        outcome:
          $ref: '#/components/schemas/OkOutcome'
        amount:
          $ref: 'common-payment-notice.yaml#/components/schemas/EuroCents'
        paTaxCode:
          $ref: 'common-payment-notice.yaml#/components/schemas/PaTaxCode'
        paymentToken:
          $ref: '#/components/schemas/PaymentToken'
        transfers:
          type: array
          maxItems: 5
          items:
            $ref: 'common-payment-notice.yaml#/components/schemas/Transfer'
      required:
        - paymentToken
      example:
        outcome: "OK"
        amount: 12345
        paTaxCode: "15376371009"
        paymentToken: "648fhg36s95jfg7DS"
        transfers:
          - paTaxCode: "15376371009"
            category: "KTM"

  # ========================================================
  # Request bodies
  # ========================================================
  requestBodies:
    # ------------------------------------------------------
    # For activateByQrCode and
    # activateByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    Activate:
      description: Request to activate payment notice
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              idempotencyKey:
                $ref: '#/components/schemas/IdempotencyKey'
              amount:
                $ref: 'common-payment-notice.yaml#/components/schemas/EuroCents'
            required:
              - idempotencyKey
              - amount
            example:
              idempotencyKey: "47583764545_Ahf479elk0"
              amount: 12345

    # ------------------------------------------------------
    # For close
    # ------------------------------------------------------
    Close:
      description: Request to close transaction
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/AllOrNothingOutcome'
              paymentTokens:
                type: array
                maxItems: 5
                items:
                  $ref: '#/components/schemas/PaymentToken'
              paymentMethod:
                $ref: 'common-payment-notice.yaml#/components/schemas/PaymentMethod'
              transactionId:
                $ref: 'common-payment-notice.yaml#/components/schemas/TransactionId'
              totalAmount:
                $ref: 'common-payment-notice.yaml#/components/schemas/EuroCents'
              fee:
                $ref: 'common-payment-notice.yaml#/components/schemas/EuroCents'
              timestampOp:
                description: Timestamp of e-money transaction
                type: string
                format: date-time
                maxLength: 19
            required:
              - outcome
              - paymentTokens
              - paymentMethod
              - transactionId
              - totalAmount
              - fee
              - timestampOp
            example:
              outcome: "OK"
              paymentTokens:
                - "648fhg36s95jfg7DS"
              paymentMethod: "PAGOBANCOMAT"
              transactionId: "517a4216840E461fB011036A0fd134E1"
              totalAmount: 12345
              fee: 50
              timestampOp: "2022-11-12T08:53:55"

    # ------------------------------------------------------
    # For receivePaymentStatus
    # ------------------------------------------------------
    PaymentStatusByNodo:
      description: Payment status communicated by the Nodo
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentStatusByNodo'
            
  # ========================================================
  # Responses
  # ========================================================
  responses:
    # ------------------------------------------------------
    # For verifyByQrCode and verifyByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    VerifyProcessed:
      description: Verify processed
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/VerifyOk'
              - $ref: '#/components/schemas/VerifyOrActivateKo'

    # ------------------------------------------------------
    # For activateByQrCode and
    # activateByTaxCodeAndNoticeNumber
    # ------------------------------------------------------
    ActivateProcessed:
      description: Activate processed
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ActivateOk'
              - $ref: '#/components/schemas/VerifyOrActivateKo'

    # ------------------------------------------------------
    # For close
    # ------------------------------------------------------
    OkCloseProcessed:
      description: Response to OK close transaction successfully processed
      headers:
        Location:
          description: URL to check the status of payment confirmation. If outcome = OK the field is present.
          required: false
          schema:
            $ref: 'common.yaml#/components/schemas/URI'
        Retry-After:
          description: Number of seconds after which to check the status of payment confirmation. If outcome = OK the field is present.
          required: false
          schema:
            $ref: 'common.yaml#/components/schemas/PositiveInteger'
        Max-Retries:
          description: Max number of retries to check the status of payment confirmation. If outcome = OK the field is present.
          required: false
          schema:
            $ref: 'common.yaml#/components/schemas/PositiveInteger'
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/AllOrNothingOutcome'
            required:
              - outcome
            example:
              outcome: "OK"

    # ------------------------------------------------------
    # For getPaymentStatus
    # ------------------------------------------------------
    PaymentStatus:
      description: Payment status received
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PaymentStatus'

    # ------------------------------------------------------
    # For receivePaymentStatus
    # ------------------------------------------------------
    PaymentStatusReceived:
      description: Payment status received
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/OkOutcome'
            required:
              - outcome
            example:
              outcome: "OK"

    TransactionNotFound:
      description: Transaction not found
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties:
              outcome:
                $ref: '#/components/schemas/TrxNotFoundOutcome'
            required:
              - outcome
            example:
              outcome: "PAYMENT_NOT_FOUND"

  # ========================================================
  # Security schemes
  # ========================================================
  securitySchemes:
    ApiKeyAuth:
      $ref: 'common.yaml#/components/securitySchemes/ApiKeyAuth'
    
    oAuth2:
      $ref: 'common.yaml#/components/securitySchemes/oAuth2'