openapi: 3.0.3
info:
  title: Fee Calculator Microservice
  description: Fee Calculator for Multi-channel Integration Layer of SW Client Project
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it
  version: 3.0.0
servers:
- url: https://mil-d-apim.azure-api.net/mil-fee-calculator
  description: DEV
paths:
  /fees:
    post:
      summary: Calculates the fee amount for a set of payment notices
      operationId: getFee
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      - name: AcquirerId
        in: header
        description: Acquirer ID assigned by PagoPA
        required: true
        schema:
          $ref: '#/components/schemas/AcquirerId'
      - name: Channel
        in: header
        description: Channel originating the request
        required: true
        schema:
          $ref: '#/components/schemas/Channel'
      - name: MerchantId
        in: header
        description: Merchant ID. Mandatory when Channel equals POS.
        required: false
        schema:
          $ref: '#/components/schemas/MerchantId'
      - name: TerminalId
        in: header
        description: ID of the terminal originating the transaction. It must be unique
          per acquirer and channel.
        required: true
        schema:
          $ref: '#/components/schemas/TerminalId'
      requestBody:
        $ref: '#/components/requestBodies/GetFee'
      responses:
        "200":
          description: Fee found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Fee not found
        "406":
          description: Not acceptable. Did you require application/json?
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - ApiKeyAuth: []
      - oAuth2:
        - getFee
components:
  schemas:
    PaymentNotice:
      required:
      - amount
      - paTaxCode
      - transfers
      type: object
      properties:
        amount:
          $ref: '#/components/schemas/EuroCents'
        paTaxCode:
          $ref: '#/components/schemas/PaTaxCode'
        transfers:
          maxItems: 5
          type: array
          items:
            $ref: '#/components/schemas/Transfer'
      additionalProperties: false
      description: Payment notice data
      example:
        amount: 12345
        paTaxCode: "15376371009"
        transfers:
        - paTaxCode: "15376371009"
          category: KTM
    UUID:
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      type: string
      description: UUID
      format: uuid
      example: d0d654e6-97da-4848-b568-99fedccb642b
    AcquirerId:
      pattern: "^\\d{1,11}$"
      type: string
      description: Acquirer ID assigned by PagoPA
      example: "4585625"
    Channel:
      type: string
      description: Channel originating the request
      example: ATM
      enum:
      - ATM
      - POS
      - TOTEM
      - CASH_REGISTER
      - CSA
    MerchantId:
      pattern: "^[0-9a-zA-Z]{1,15}$"
      type: string
      description: Merchant ID. Mandatory when Channel equals POS.
      example: 28405fHfk73x88D
    TerminalId:
      pattern: "^[0-9a-zA-Z]{1,8}$"
      type: string
      description: ID of the terminal originating the transaction. It must be unique
        per acquirer and channel.
      example: 0aB9wXyZ
    EuroCents:
      maximum: 99999999999
      minimum: 1
      type: integer
      description: Amount in euro cents
      format: int64
      example: 12345
    Errors:
      required:
      - errors
      type: object
      properties:
        errors:
          maxItems: 32
          type: array
          items:
            $ref: '#/components/schemas/Error'
      additionalProperties: false
      description: List of errors
      example:
        errors:
        - 00000000A
        - "001000001"
    Error:
      pattern: "^[A-F0-9]{9}$"
      type: string
      description: Error code
      example: "001000005"
    PaymentMethod:
      type: string
      description: Method used to pay notice/s
      example: PAGOBANCOMAT
      enum:
      - PAGOBANCOMAT
      - DEBIT_CARD
      - CREDIT_CARD
      - PAYMENT_CARD
      - BANK_ACCOUNT
      - CASH
    PaTaxCode:
      pattern: "^[0-9]{11}$"
      type: string
      description: Tax code of the creditor company
      example: "15376371009"
    Transfer:
      required:
      - category
      - paTaxCode
      type: object
      properties:
        paTaxCode:
          $ref: '#/components/schemas/PaTaxCode'
        category:
          $ref: '#/components/schemas/Category'
      additionalProperties: false
      description: Transfer essential data
      example:
        paTaxCode: "15376371009"
        category: KTM
    Category:
      pattern: "^[ -~]{0,1024}$"
      type: string
      description: Transfer category
      example: KTM
    inline_response_200:
      required:
      - fee
      type: object
      properties:
        fee:
          $ref: '#/components/schemas/EuroCents'
      additionalProperties: false
      example:
        fee: 50
  responses:
    FeeFound:
      description: Fee found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_response_200'
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    RequestId:
      name: RequestId
      in: header
      description: Request Id that will be logged by services
      required: true
      schema:
        $ref: '#/components/schemas/UUID'
    Version:
      name: Version
      in: header
      description: Version of the required API
      required: false
      schema:
        maxLength: 64
        pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
          d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
          +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        type: string
        example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
    AcquirerId:
      name: AcquirerId
      in: header
      description: Acquirer ID assigned by PagoPA
      required: true
      schema:
        $ref: '#/components/schemas/AcquirerId'
    Channel:
      name: Channel
      in: header
      description: Channel originating the request
      required: true
      schema:
        $ref: '#/components/schemas/Channel'
    MerchantId:
      name: MerchantId
      in: header
      description: Merchant ID. Mandatory when Channel equals POS.
      required: false
      schema:
        $ref: '#/components/schemas/MerchantId'
    TerminalId:
      name: TerminalId
      in: header
      description: ID of the terminal originating the transaction. It must be unique
        per acquirer and channel.
      required: true
      schema:
        $ref: '#/components/schemas/TerminalId'
  requestBodies:
    GetFee:
      description: Request to get fee
      content:
        application/json:
          schema:
            required:
            - notices
            - paymentMethod
            type: object
            properties:
              paymentMethod:
                $ref: '#/components/schemas/PaymentMethod'
              notices:
                maxItems: 5
                type: array
                items:
                  $ref: '#/components/schemas/PaymentNotice'
            additionalProperties: false
            description: Request to get fee
            example:
              paymentMethod: PAGOBANCOMAT
              notices:
              - amount: 12345
                paTaxCode: "15376371009"
                transfers:
                - paTaxCode: "15376371009"
                  category: KTM
  securitySchemes:
    oAuth2:
      type: oauth2
      description: This API uses OAuth2
      flows:
        password:
          tokenUrl: ../mil-idp/token
          scopes:
            verifyByQrCode: Verifies a payment notice by QR-code
            activateByQrCode: Activats the payment of a notice by QR-code
            verifyByTaxCodeAndNoticeNumber: Verifies a payment notice by PA tax code
              and notice number
            activateByTaxCodeAndNoticeNumber: Activates the payment of a notice by
              PA tax code and notice number
            preCloseOrAbort: Pre-closes or aborts the payment of a set of notices
            close: Closes the payment of a set of notices
            getPaymentStatus: Retrieves the status of the payment of a set of payment
              notices
            getLastTransactions: Gets last 30 transactions executed by the client
              in the last 30 days
            getFee: Calculates the fee amount for a set of payment notices
            getServices: Returns the list of services available for end-users
            deleteSessionById: Deletes a session by ID
            createSession: Creates a session
            checkPairingStatus: Retrieves the pairing status with IO
            accept: Stores the acceptance of T&C for the user identified by the tax
              code stored in the session
            presaveExplicit: Pre-saves the payment card in the internal Wallet
            getPreset: Returns the details of a preset operation that has not yet
              been executed
    ApiKeyAuth:
      type: apiKey
      description: This API uses API key when it is invoked by a server application
      name: API-Key
      in: header
