openapi: 3.0.3
info:
  title: Preset Microservice
  description: This microservice handles preset operations
  contact:
    name: Antonio Tarricone
    email: antonio.tarricone@pagopa.it
  version: 1.0.0
servers:
- url: https://mil-d-apim.azure-api.net/mil-preset
  description: DEV
paths:
  /terminals:
    post:
      summary: Subscribes a terminal to handle preset operations
      operationId: subscribe
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      - name: AcquirerId
        in: header
        description: "Acquirer ID assigned by PagoPA. If the request comes from a\
          \ terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/AcquirerId'
      - name: Channel
        in: header
        description: "Channel originating the request. If the request comes from a\
          \ terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Channel'
      - name: MerchantId
        in: header
        description: "Merchant ID. If the request comes from a POS, the parameter\
          \ is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/MerchantId'
      - name: TerminalId
        in: header
        description: "ID of the terminal originating the transaction. If the request\
          \ comes from a terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/TerminalId'
      requestBody:
        $ref: '#/components/requestBodies/Subscribe'
      responses:
        "201":
          description: Terminal subscribed successfully or already subscribed
          headers:
            Location:
              description: URL to subscribed terminal
              required: true
              style: simple
              explode: false
              schema:
                $ref: '#/components/schemas/URI'
              example:
                Location: /terminals/15376371009/x46tr3
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token or API key is missing or invalid
        "403":
          description: Forbidden
        "409":
          description: Terminal subscribed successfully or already subscribed
          headers:
            Location:
              description: URL to subscribed terminal
              required: true
              style: simple
              explode: false
              schema:
                $ref: '#/components/schemas/URI'
              example:
                Location: /terminals/15376371009/x46tr3
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - oAuth2:
        - subscribe
  /terminals/{paTaxCode}/{subscriberId}:
    delete:
      summary: Unsubscribes a terminal to handle preset operations
      operationId: unsubscriberForPreset
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      - name: AcquirerId
        in: header
        description: "Acquirer ID assigned by PagoPA. If the request comes from a\
          \ terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/AcquirerId'
      - name: Channel
        in: header
        description: "Channel originating the request. If the request comes from a\
          \ terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Channel'
      - name: MerchantId
        in: header
        description: "Merchant ID. If the request comes from a POS, the parameter\
          \ is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/MerchantId'
      - name: TerminalId
        in: header
        description: "ID of the terminal originating the transaction. If the request\
          \ comes from a terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/TerminalId'
      - name: paTaxCode
        in: path
        description: Tax code of the creditor company
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/PaTaxCode'
      - name: subscriberId
        in: path
        description: ID assigned to subscribed terminal
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/SubscriberId'
      responses:
        "204":
          description: Terminal unsubscribed correctly
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token or API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Subscription not found
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - oAuth2:
        - unsubscribe
  /terminals/{paTaxCode}/:
    get:
      summary: Returns the list of subscribed terminals
      operationId: getSubscribers
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      - name: paTaxCode
        in: path
        description: Tax code of the creditor company
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/PaTaxCode'
      responses:
        "200":
          description: List of subscribed terminals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscribers'
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token or API key is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - oAuth2:
        - getSubscribers
  /presets:
    post:
      summary: Creates a preset operation
      operationId: createPreset
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      requestBody:
        $ref: '#/components/requestBodies/CreatePreset'
      responses:
        "201":
          description: Preset operation created successfully
          headers:
            Location:
              description: URL to preset operation
              required: true
              style: simple
              explode: false
              schema:
                $ref: '#/components/schemas/URI'
              example:
                Location: /terminals/15376371009/x46tr3/d0d654e6-97da-4848-b568-99fedccb642b
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token or API key is missing or invalid
        "403":
          description: Forbidden
        "415":
          description: Unsupported media type. Did you provide application/json?
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - oAuth2:
        - createPreset
  /presets/{paTaxCode}/{subscriberId}:
    get:
      summary: Returns preset operations for a specific subscriber
      operationId: getPresets
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      - name: paTaxCode
        in: path
        description: Tax code of the creditor company
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/PaTaxCode'
      - name: subscriberId
        in: path
        description: ID assigned to subscribed terminal
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/SubscriberId'
      responses:
        "200":
          description: List of preset operations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Presets'
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token or API key is missing or invalid
        "403":
          description: Forbidden
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - oAuth2:
        - getPresets
  /presets/{paTaxCode}/{subscriberId}/last_to_execute:
    get:
      summary: Returns last preset operation to execute
      operationId: getLastPresetToExecute
      parameters:
      - name: RequestId
        in: header
        description: Request Id that will be logged by services
        required: true
        schema:
          $ref: '#/components/schemas/UUID'
      - name: Version
        in: header
        description: Version of the required API
        required: false
        schema:
          maxLength: 64
          pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
            d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
            +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          type: string
          example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
      - name: AcquirerId
        in: header
        description: "Acquirer ID assigned by PagoPA. If the request comes from a\
          \ terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/AcquirerId'
      - name: Channel
        in: header
        description: "Channel originating the request. If the request comes from a\
          \ terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/Channel'
      - name: MerchantId
        in: header
        description: "Merchant ID. If the request comes from a POS, the parameter\
          \ is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/MerchantId'
      - name: TerminalId
        in: header
        description: "ID of the terminal originating the transaction. If the request\
          \ comes from a terminal, the parameter is mandatory."
        required: false
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/TerminalId'
      - name: paTaxCode
        in: path
        description: Tax code of the creditor company
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/PaTaxCode'
      - name: subscriberId
        in: path
        description: ID assigned to subscribed terminal
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/SubscriberId'
      responses:
        "200":
          description: Last preset to execute
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Preset'
        "400":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        "401":
          description: Access token or API key is missing or invalid
        "403":
          description: Forbidden
        "404":
          description: Not found
        "406":
          description: Not acceptable. Did you require application/json?
        "429":
          description: Too many request
        "500":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        default:
          description: Unexpected error
      security:
      - oAuth2:
        - getLastPresetToExecute
components:
  schemas:
    Status:
      type: string
      description: Operation status
      example: TO_EXECUTE
      enum:
      - TO_EXECUTE
      - EXECUTED
    Type:
      type: string
      description: Opertion type
      example: PAYMENT_NOTICE
      enum:
      - PAYMENT_NOTICE
    SubscriberId:
      pattern: "^[0-9a-z]{6}$"
      type: string
      description: Subscriber ID
      example: x46tr3
    Operation:
      required:
      - operationType
      - paTaxCode
      - subscriberId
      type: object
      properties:
        operationType:
          $ref: '#/components/schemas/Type'
        paTaxCode:
          $ref: '#/components/schemas/PaTaxCode'
        subscriberId:
          $ref: '#/components/schemas/SubscriberId'
      additionalProperties: true
      description: Generic operation
    OperationDetails:
      required:
      - creationTimestamp
      - presetId
      - status
      - statusTimestamp
      type: object
      properties:
        presetId:
          $ref: '#/components/schemas/UUID'
        creationTimestamp:
          maxLength: 19
          type: string
          description: Creation timestamp
          format: date-time
        status:
          $ref: '#/components/schemas/Status'
        statusTimestamp:
          maxLength: 19
          type: string
          description: Timestamp of the last status update
          format: date-time
      additionalProperties: true
      description: Details of a generic operation
    PaymentNotice:
      description: Operation of payment of a notice
      example:
        operationType: PAYMENT_NOTICE
        paTaxCode: "15376371009"
        subscriberId: x46tr3
        noticeTaxCode: "15376371009"
        noticeNumber: "485564829563528563"
      allOf:
      - $ref: '#/components/schemas/Operation'
      - required:
        - noticeNumber
        - noticeTaxCode
        type: object
        properties:
          noticeTaxCode:
            $ref: '#/components/schemas/PaTaxCode'
          noticeNumber:
            $ref: '#/components/schemas/NoticeNumber'
        additionalProperties: true
    PaymentNoticeDetails:
      description: Details of a payment notice as preset operation
      example:
        operationType: PAYMENT_NOTICE
        paTaxCode: "15376371009"
        subscriberId: x46tr3
        noticeTaxCode: "15376371009"
        noticeNumber: "485564829563528563"
        presetId: d0d654e6-97da-4848-b568-99fedccb642b
        creationTimestamp: 2023-05-05T16:35:30
        status: EXECUTED
        statusTimestamp: 2023-05-05T16:36:30
        statusDetails:
          transactionId: 517a4216840E461fB011036A0fd134E1
          acquirerId: "4585625"
          channel: POS
          merchantId: 28405fHfk73x88D
          terminalId: 0aB9wXyZ
          insertTimestamp: 2023-04-11T16:20:34
          notices:
          - paymentToken: 648fhg36s95jfg7DS
            paTaxCode: "15376371009"
            noticeNumber: "485564829563528563"
            amount: 12345
            description: Health ticket for chest x-ray
            company: ASL Roma
            office: Ufficio di Roma
          totalAmount: 12395
          fee: 50
          status: PRE_CLOSE
      allOf:
      - $ref: '#/components/schemas/PaymentNotice'
      - $ref: '#/components/schemas/OperationDetails'
      - required:
        - statusDetails
        type: object
        properties:
          statusDetails:
            $ref: '#/components/schemas/PaymentStatus'
        additionalProperties: true
    Subscribe:
      type: object
      properties:
        paTaxCode:
          $ref: '#/components/schemas/PaTaxCode'
        label:
          description: Mnemonic terminal label
          allOf:
          - $ref: '#/components/schemas/Message'
      additionalProperties: false
      description: Request to subscribe a terminal to handle preset operations
      example:
        paTaxCode: "15376371009"
        label: Reception POS
    Subscriber:
      required:
      - acquirerId
      - channel
      - label
      - lastUsageTimestamp
      - merchantId
      - paTaxCode
      - subscriberId
      - subscriptionTimestamp
      - terminalId
      type: object
      properties:
        acquirerId:
          $ref: '#/components/schemas/AcquirerId'
        channel:
          $ref: '#/components/schemas/Channel'
        merchantId:
          $ref: '#/components/schemas/MerchantId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        paTaxCode:
          $ref: '#/components/schemas/PaTaxCode'
        subscriberId:
          $ref: '#/components/schemas/SubscriberId'
        label:
          description: Mnemonic terminal label
          allOf:
          - $ref: '#/components/schemas/Message'
        subscriptionTimestamp:
          maxLength: 19
          type: string
          description: Subscription timestamp
          format: date-time
        lastUsageTimestamp:
          maxLength: 19
          type: string
          description: Last usage timestamp
          format: date-time
      additionalProperties: false
      description: Subscriber data
      example:
        acquirerId: "4585625"
        channel: POS
        merchantId: 28405fHfk73x88D
        terminalId: 0aB9wXyZ
        paTaxCode: "15376371009"
        subscriberId: x46tr3
        label: Reception POS
        subscriptionTimestamp: 2023-05-05T09:31:33
        lastUsageTimestamp: 2023-05-08T10:55:57
    Subscribers:
      required:
      - subscribers
      type: object
      properties:
        subscribers:
          type: array
          items:
            $ref: '#/components/schemas/Subscriber'
      additionalProperties: false
      description: List of subscribed terminals
      example:
        subscribers:
        - acquirerId: "4585625"
          channel: POS
          merchantId: 28405fHfk73x88D
          terminalId: 0aB9wXyZ
          paTaxCode: "15376371009"
          subscriberId: x46tr3
          label: Reception POS
          subscriptionTimestamp: 2023-05-05T09:31:33
          lastUsageTimestamp: 2023-05-08T10:55:57
    Preset:
      description: Preset operation with detailed status data
      discriminator:
        propertyName: operationType
        mapping:
          PAYMENT_NOTICE: '#/components/schemas/PaymentNoticeDetails'
      oneOf:
      - $ref: '#/components/schemas/PaymentNoticeDetails'
    Presets:
      required:
      - presets
      type: object
      properties:
        presets:
          type: array
          items:
            $ref: '#/components/schemas/Preset'
      additionalProperties: false
      description: List of preset operations
    UUID:
      pattern: "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
      type: string
      description: UUID
      format: uuid
      example: d0d654e6-97da-4848-b568-99fedccb642b
    AcquirerId:
      pattern: "^\\d{1,11}$"
      type: string
      description: Acquirer ID assigned by PagoPA
      example: "4585625"
    Channel:
      type: string
      description: Channel originating the request
      example: ATM
      enum:
      - ATM
      - POS
      - TOTEM
      - CASH_REGISTER
      - CSA
    MerchantId:
      pattern: "^[0-9a-zA-Z]{1,15}$"
      type: string
      description: Merchant ID. Mandatory when Channel equals POS.
      example: 28405fHfk73x88D
    TerminalId:
      pattern: "^[0-9a-zA-Z]{1,8}$"
      type: string
      description: ID of the terminal originating the transaction. It must be unique
        per acquirer and channel.
      example: 0aB9wXyZ
    URI:
      pattern: "^[ -~]{1,2048}$"
      type: string
      description: URI
      format: uri
    Errors:
      required:
      - errors
      type: object
      properties:
        errors:
          maxItems: 32
          type: array
          items:
            $ref: '#/components/schemas/Error'
      additionalProperties: false
      description: List of errors
      example:
        errors:
        - 00000000A
        - "001000001"
    Error:
      pattern: "^[A-F0-9]{9}$"
      type: string
      description: Error code
      example: "001000005"
    PaTaxCode:
      pattern: "^[0-9]{11}$"
      type: string
      description: Tax code of the creditor company
      example: "15376371009"
    NoticeNumber:
      pattern: "^[0-9]{18}$"
      type: string
      description: Notice number
      example: "485564829563528563"
    PaymentStatus:
      required:
      - acquirerId
      - channel
      - insertTimestamp
      - notices
      - status
      - terminalId
      - totalAmount
      - transactionId
      type: object
      properties:
        transactionId:
          $ref: '#/components/schemas/TransactionId'
        acquirerId:
          $ref: '#/components/schemas/AcquirerId'
        channel:
          $ref: '#/components/schemas/Channel'
        merchantId:
          $ref: '#/components/schemas/MerchantId'
        terminalId:
          $ref: '#/components/schemas/TerminalId'
        insertTimestamp:
          maxLength: 19
          type: string
          description: Record registration timestamp (timestamp of pre-close or abort)
          format: date-time
        notices:
          maxItems: 5
          type: array
          description: Details of payment notices
          items:
            $ref: '#/components/schemas/PaymentNoticeFullDetails'
        totalAmount:
          $ref: '#/components/schemas/EuroCents'
        fee:
          $ref: '#/components/schemas/EuroCents'
        status:
          $ref: '#/components/schemas/TransactionStatus'
        paymentMethod:
          $ref: '#/components/schemas/PaymentMethod'
        paymentTimestamp:
          maxLength: 19
          type: string
          description: Timestamp of e-money transaction
          format: date-time
        closeTimestamp:
          maxLength: 19
          type: string
          description: Timestamp of the confirmation from the Client
          format: date-time
        paymentDate:
          maxLength: 19
          type: string
          description: Notification timestamp
          format: date-time
        callbackTimestamp:
          maxLength: 19
          type: string
          description: Timestamp of the callback (sendPaymentResult) from the Nodo.
          format: date-time
      additionalProperties: false
      description: Payment status
      example:
        transactionId: 517a4216840E461fB011036A0fd134E1
        acquirerId: "4585625"
        channel: POS
        merchantId: 28405fHfk73x88D
        terminalId: 0aB9wXyZ
        insertTimestamp: 2023-04-11T16:20:34
        notices:
        - paymentToken: 648fhg36s95jfg7DS
          paTaxCode: "15376371009"
          noticeNumber: "485564829563528563"
          amount: 12345
          description: Health ticket for chest x-ray
          company: ASL Roma
          office: Ufficio di Roma
        totalAmount: 12395
        fee: 50
        status: PRE_CLOSE
    PaymentNoticeFullDetails:
      required:
      - noticeNumber
      - paTaxCode
      - paymentToken
      type: object
      properties:
        paymentToken:
          $ref: '#/components/schemas/PaymentToken'
        paTaxCode:
          $ref: '#/components/schemas/PaTaxCode'
        noticeNumber:
          $ref: '#/components/schemas/NoticeNumber'
        amount:
          $ref: '#/components/schemas/EuroCents'
        description:
          $ref: '#/components/schemas/Description'
        company:
          $ref: '#/components/schemas/Company'
        office:
          $ref: '#/components/schemas/Office'
        creditorReferenceId:
          $ref: '#/components/schemas/CreditorReferenceId'
        debtor:
          $ref: '#/components/schemas/Debtor'
      additionalProperties: false
      description: Full details of the payment notice
      example:
        paymentToken: 648fhg36s95jfg7DS
        paTaxCode: "15376371009"
        noticeNumber: "485564829563528563"
        amount: 12345
        description: Health ticket for chest x-ray
        company: ASL Roma
        office: Ufficio di Roma
        creditorReferenceId: 4839d50603fssfW5X
        debtor: Mario Rossi
    PaymentToken:
      pattern: "^[ -~]{1,35}$"
      type: string
      description: ID of the payment activation
      example: 648fhg36s95jfg7DS
    Description:
      pattern: "^[ -~]{1,140}$"
      type: string
      description: Payment notice description
      example: Health ticket for chest x-ray
    Company:
      pattern: "^[ -~]{1,140}$"
      type: string
      description: Name of the creditor company
      example: ASL Roma
    Office:
      pattern: "^[ -~]{1,140}$"
      type: string
      description: Name of the creditor company office
      example: Ufficio di Roma
    CreditorReferenceId:
      pattern: "^[ -~]{1,35}$"
      type: string
      description: ID for the creditor company
      example: 4839d50603fssfW5X
    Debtor:
      pattern: "^[ -~]{0,1024}$"
      type: string
      description: Debtor unstructured data
      example: Mario Rossi
    TransactionStatus:
      type: string
      description: Status of the transaction
      example: CLOSED
      enum:
      - PRE_CLOSE
      - PENDING
      - ERROR_ON_CLOSE
      - CLOSED
      - ERROR_ON_RESULT
      - ERROR_ON_PAYMENT
      - ABORTED
    Message:
      pattern: "^[\x01-퟿-�က0-ჿFF]{1,256}$"
      type: string
      description: Generic message containing XML 1.1 allowed characters
      example: Session has not yet been created
    TransactionId:
      pattern: "^[a-zA-Z0-9]{32}$"
      type: string
      description: Transaction ID
      example: 517a4216840E461fB011036A0fd134E1
    EuroCents:
      maximum: 99999999999
      minimum: 1
      type: integer
      description: Amount in euro cents
      format: int64
      example: 12345
    PaymentMethod:
      type: string
      description: Method used to pay notice/s
      example: PAGOBANCOMAT
      enum:
      - PAGOBANCOMAT
      - DEBIT_CARD
      - CREDIT_CARD
      - PAYMENT_CARD
      - BANK_ACCOUNT
      - CASH
  responses:
    PresetCreated:
      description: Preset operation created successfully
      headers:
        Location:
          description: URL to preset operation
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/URI'
          example:
            Location: /terminals/15376371009/x46tr3/d0d654e6-97da-4848-b568-99fedccb642b
    Subscribe:
      description: Terminal subscribed successfully or already subscribed
      headers:
        Location:
          description: URL to subscribed terminal
          required: true
          style: simple
          explode: false
          schema:
            $ref: '#/components/schemas/URI'
          example:
            Location: /terminals/15376371009/x46tr3
    Subscribes:
      description: List of subscribed terminals
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subscribers'
    Presets:
      description: List of preset operations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Presets'
    Preset:
      description: Last preset to execute
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Preset'
    Error:
      description: Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Errors'
  parameters:
    AcquirerId:
      name: AcquirerId
      in: header
      description: "Acquirer ID assigned by PagoPA. If the request comes from a terminal,\
        \ the parameter is mandatory."
      required: false
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/AcquirerId'
    Channel:
      name: Channel
      in: header
      description: "Channel originating the request. If the request comes from a terminal,\
        \ the parameter is mandatory."
      required: false
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/Channel'
    MerchantId:
      name: MerchantId
      in: header
      description: "Merchant ID. If the request comes from a POS, the parameter is\
        \ mandatory."
      required: false
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/MerchantId'
    TerminalId:
      name: TerminalId
      in: header
      description: "ID of the terminal originating the transaction. If the request\
        \ comes from a terminal, the parameter is mandatory."
      required: false
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/TerminalId'
    PaTaxCode:
      name: paTaxCode
      in: path
      description: Tax code of the creditor company
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/PaTaxCode'
    SubscriberId:
      name: subscriberId
      in: path
      description: ID assigned to subscribed terminal
      required: true
      style: simple
      explode: false
      schema:
        $ref: '#/components/schemas/SubscriberId'
    RequestId:
      name: RequestId
      in: header
      description: Request Id that will be logged by services
      required: true
      schema:
        $ref: '#/components/schemas/UUID'
    Version:
      name: Version
      in: header
      description: Version of the required API
      required: false
      schema:
        maxLength: 64
        pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
          d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
          +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        type: string
        example: 1.0.0-alpha-a.b-c-somethinglong+build.1-aef.1-its-okay
  requestBodies:
    CreatePreset:
      description: Request to create as preset operation
      content:
        application/json:
          schema:
            discriminator:
              propertyName: operationType
              mapping:
                PAYMENT_NOTICE: '#/components/schemas/PaymentNotice'
            oneOf:
            - $ref: '#/components/schemas/PaymentNotice'
    Subscribe:
      description: Request to subscribe a terminal to handle preset operations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subscribe'
  securitySchemes:
    oAuth2:
      type: oauth2
      description: This API uses OAuth2
      flows:
        password:
          tokenUrl: ../mil-idp/token
          scopes:
            verifyByQrCode: Verifies a payment notice by QR-code
            activateByQrCode: Activats the payment of a notice by QR-code
            verifyByTaxCodeAndNoticeNumber: Verifies a payment notice by PA tax code
              and notice number
            activateByTaxCodeAndNoticeNumber: Activates the payment of a notice by
              PA tax code and notice number
            preCloseOrAbort: Pre-closes or aborts the payment of a set of notices
            close: Closes the payment of a set of notices
            getPaymentStatus: Retrieves the status of the payment of a set of payment
              notices
            getLastTransactions: Gets last 30 transactions executed by the client
              in the last 30 days
            getFee: Calculates the fee amount for a set of payment notices
            getServices: Returns the list of services available for end-users
            deleteSessionById: Deletes a session by ID
            createSession: Creates a session
            checkPairingStatus: Retrieves the pairing status with IO
            accept: Stores the acceptance of T&C for the user identified by the tax
              code stored in the session
            presaveExplicit: Pre-saves the payment card in the internal Wallet
            getPreset: Returns the details of a preset operation that has not yet
              been executed
